name: Maven Nexus Publish Workflow
description: A composite action to ensure that code is sent to Nexus repository

# Inputs
inputs:
  nexus_repo_id:
    description: "Nexus Repository ID" 
    required: false
    default: "maven-snapshots"
  nexus_repo_username:
    description: "Nexus Repository Username" 
    required: false 
    default: "admin"
  nexus_repo_password:
    description: "Nexus Repository Password"  
    required: true
  nexus_repo_url:
    description: "Nexus Repository URL"
    required: false 
    default: "https://nexus.tinkarbuild.com" 
  nexus_profile: 
    description: "Nexus Profile"
    default: "inject-application-properties"
  repo_name: 
    description: "Repo Name"
    required: true
  branch_name: 
    description: "Branch Name" 
    required: true 
  working_directory:
    description: "Working Directory"
    required: false


runs:
  using: "composite" 
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: ${{inputs.repo_name}}
        ref: ${{inputs.branch_name}}
    
    - name: Build Protoc Docker container
      uses: docker/build-push-action@v6
      if: github.event.repository.name == 'tinkar-schema'
      with:
        push: false
        context: .
        file: protoc.dockerfile
        tags: tinkar-schema-protoc:latest
  
  
    - name: Generate Java Code
      shell: bash
      if: github.event.repository.name == 'tinkar-schema'
      run: |
        sudo docker run -v ./src/main/java-generated:/home/proto-builder/src/main/java-generated --rm tinkar-schema-protoc:latest
        
    - name: list java code
      shell: bash
      if: github.event.repository.name == 'tinkar-schema'
      run: |
        ls src/main/java-generated

    - name: Extract Version
      id: get_current_version
      shell: bash
      run: |
          echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      working-directory: ${{inputs.working_directory}}
    
    - name: Nexus Repo Release ID
      id: nexusRepoID
      if: ${{ !contains(steps.get_current_version.outputs.POM_VERSION, '-SNAPSHOT')}}
      shell: bash
      run: |
            echo "NEXUS_RELEASE_ID=maven-releases" >> $GITHUB_OUTPUT

    - name: Maven Settings File
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        servers: '[{"id": "${{ steps.nexusRepoID.outputs.NEXUS_RELEASE_ID || inputs.nexus_repo_id }}", "username": "${{inputs.nexus_repo_username}}", "password": "${{inputs.nexus_repo_password}}"}]'
        profiles: '[{"id": "${{inputs.nexus_profile}}", "properties": {"altDeploymentRepository": "${{ steps.nexusRepoID.outputs.NEXUS_RELEASE_ID || inputs.nexus_repo_id }}::${{ inputs.nexus_repo_url }}/repository/${{ steps.nexusRepoID.outputs.NEXUS_RELEASE_ID || inputs.nexus_repo_id }}"}}]'
        active_profiles: '["${{inputs.nexus_profile}}"]' 
        output_file: .m2/settings.xml

    - name: Deploy To Nexus
      shell: bash
      if: ${{github.event.repository.name}} != 'jpms-deps'
      run: |
           mvn deploy \
            --batch-mode \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -DskipTests \
            -DskipITs \
            -s '/home/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/.m2/settings.xml' \
            -DrepositoryId='${{ steps.nexusRepoID.outputs.NEXUS_RELEASE_ID || inputs.nexus_repo_id }}' 

    - name: Deploy To Nexus (JPMS-DEPS)
      shell: bash
      if: ${{github.event.repository.name}} == 'jpms-deps'
      run: |
          mvn deploy \
          --batch-mode \
          -e \
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
          -DskipTests \
          -DskipITs \
          -s '/home/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/.m2/settings.xml' \
          -DrepositoryId='${{ steps.nexusRepoID.outputs.NEXUS_RELEASE_ID || inputs.nexus_repo_id }}' 
      working-directory: ${{inputs.working_directory}}


